/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating graph
Downloading Time Series traffic data set...
Starting new HTTPS connection (1): github.com:443
https://github.com:443 "GET /laiguokun/multivariate-time-series-data/blob/master/traffic/traffic.txt.gz?raw=true HTTP/1.1" 302 None
https://github.com:443 "GET /laiguokun/multivariate-time-series-data/raw/master/traffic/traffic.txt.gz HTTP/1.1" 302 169
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /laiguokun/multivariate-time-series-data/master/traffic/traffic.txt.gz HTTP/1.1" 200 29310512
split is [0, 0.6, 0.8, 1]
rse = 0.05709034691389371
100% 10526/10526 [00:42<00:00, 249.38it/s]
100% 3509/3509 [00:14<00:00, 243.00it/s]
100% 3509/3509 [00:13<00:00, 253.91it/s]
Building graph
Loading data from ./data/traffic6/train.tfrecords
Building optimizer
2019-08-22 17:03:38.800395: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-08-22 17:03:38.800640: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x276f480 executing computations on platform Host. Devices:
2019-08-22 17:03:38.800672: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-22 17:03:38.802883: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-22 17:03:38.955169: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.955673: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x276f100 executing computations on platform CUDA. Devices:
2019-08-22 17:03:38.955701: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-08-22 17:03:38.955960: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.956320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-22 17:03:38.956660: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:03:38.957917: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:03:38.959083: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 17:03:38.959416: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 17:03:38.960790: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 17:03:38.961830: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 17:03:38.964983: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-22 17:03:38.965135: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.965587: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.965933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-22 17:03:38.966003: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:03:38.967159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 17:03:38.967189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-22 17:03:38.967201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-22 17:03:38.967500: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.967922: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:03:38.968303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2019-08-22 17:03:39.951464: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Loading weights
Loading model with fresh parameters
# of trainable parameters: 1171663
Started training
Downloading Time Series traffic data set...
split is [0, 0.6, 0.8, 1]
rse = 0.05709034691389371
Building graph
Loading data from ./data/traffic6/validation.tfrecords
2019-08-22 17:04:17.141785: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:04:17.142273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-22 17:04:17.142385: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:04:17.142417: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:04:17.142456: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 17:04:17.142480: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 17:04:17.142504: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 17:04:17.142527: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 17:04:17.142552: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-22 17:04:17.142641: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:04:17.143053: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:04:17.143435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-22 17:04:17.143474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 17:04:17.143488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-22 17:04:17.143499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-22 17:04:17.143770: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:04:17.144173: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:04:17.144567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)


Epoch: 1
2019-08-22 17:04:32.328498: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:04:39.804442: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 329, loss: 0.07350, epoch time: 82.523s
Saving model, step 329
Loading saved model from ./models/model_tf/model.ckpt-329
validation loss: 0.04815, validation rse: 1.01289, validation corr: 0.43112


Epoch: 2
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 658, loss: 0.04122, epoch time: 67.402s
Saving model, step 658
Loading saved model from ./models/model_tf/model.ckpt-658
validation loss: 0.03611, validation rse: 0.82480, validation corr: 0.54690


Epoch: 3
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 987, loss: 0.03509, epoch time: 63.516s
Saving model, step 987
Loading saved model from ./models/model_tf/model.ckpt-987
validation loss: 0.03352, validation rse: 0.78800, validation corr: 0.60407


Epoch: 4
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 1316, loss: 0.03226, epoch time: 72.841s
Saving model, step 1316
Loading saved model from ./models/model_tf/model.ckpt-1316
validation loss: 0.03239, validation rse: 0.77349, validation corr: 0.63933


Epoch: 5
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 1645, loss: 0.03057, epoch time: 85.111s
Saving model, step 1645
Loading saved model from ./models/model_tf/model.ckpt-1645
validation loss: 0.03142, validation rse: 0.75914, validation corr: 0.65822


Epoch: 6
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 1974, loss: 0.02940, epoch time: 66.563s
Saving model, step 1974
Loading saved model from ./models/model_tf/model.ckpt-1974
validation loss: 0.03038, validation rse: 0.74131, validation corr: 0.66773


Epoch: 7
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 2303, loss: 0.02853, epoch time: 87.126s
Saving model, step 2303
Loading saved model from ./models/model_tf/model.ckpt-2303
validation loss: 0.03012, validation rse: 0.74097, validation corr: 0.67963


Epoch: 8
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 2632, loss: 0.02776, epoch time: 69.110s
Saving model, step 2632
Loading saved model from ./models/model_tf/model.ckpt-2632
validation loss: 0.03058, validation rse: 0.74752, validation corr: 0.69002


Epoch: 9
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 2961, loss: 0.02712, epoch time: 73.086s
Saving model, step 2961
Loading saved model from ./models/model_tf/model.ckpt-2961
validation loss: 0.02874, validation rse: 0.71702, validation corr: 0.69519


Epoch: 10
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 3290, loss: 0.02667, epoch time: 65.846s
Saving model, step 3290
Loading saved model from ./models/model_tf/model.ckpt-3290
validation loss: 0.02844, validation rse: 0.71121, validation corr: 0.69989
Saving model as ./saved_models/TF_16_10_3_100
Stop
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating graph
Downloading Time Series traffic data set...
split is [0, 0.6, 0.8, 1]
rse = 0.05709034691389371
Building graph
Loading data from ./data/traffic6/test.tfrecords
2019-08-22 17:35:01.661310: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-08-22 17:35:01.661552: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1955480 executing computations on platform Host. Devices:
2019-08-22 17:35:01.661586: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-22 17:35:01.674819: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-22 17:35:01.839176: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.839748: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1955100 executing computations on platform CUDA. Devices:
2019-08-22 17:35:01.839792: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-08-22 17:35:01.840111: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.840520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-22 17:35:01.840959: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:35:01.842342: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:35:01.843631: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 17:35:01.844070: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 17:35:01.845603: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 17:35:01.846827: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 17:35:01.850426: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-22 17:35:01.850616: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.851076: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.851434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-22 17:35:01.851521: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:35:01.852754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 17:35:01.852783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-22 17:35:01.852795: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-22 17:35:01.853124: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.853544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:35:01.853940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2019-08-22 17:35:02.047475: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Loading weights
Loading saved model from ./models/model_tf/model.ckpt-3290
# of trainable parameters: 1171663
Started testing
2019-08-22 17:35:06.687219: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:35:09.755698: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
test rse: 0.76371, test corr: 0.67662
Stop
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating graph
Downloading Time Series traffic data set...
split is [0, 0.6, 0.8, 1]
rse = 0.05709034691389371
Building graph
Loading data from ./data/traffic6/train.tfrecords
Building optimizer
2019-08-22 17:37:40.904205: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-08-22 17:37:40.904414: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27b5480 executing computations on platform Host. Devices:
2019-08-22 17:37:40.904445: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-22 17:37:40.906604: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-22 17:37:41.067534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.068086: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27b5100 executing computations on platform CUDA. Devices:
2019-08-22 17:37:41.068120: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2019-08-22 17:37:41.068412: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.068857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-22 17:37:41.069231: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:37:41.070611: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:37:41.071821: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 17:37:41.072275: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 17:37:41.073754: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 17:37:41.074849: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 17:37:41.078187: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-22 17:37:41.078320: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.078736: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.079111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-22 17:37:41.079189: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:37:41.080320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 17:37:41.080346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-22 17:37:41.080357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-22 17:37:41.080677: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.081107: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:37:41.081467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2019-08-22 17:37:42.106773: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Loading weights
Loading saved model from ./models/model_tf/model.ckpt-3290
# of trainable parameters: 1171663
Started training
Downloading Time Series traffic data set...
split is [0, 0.6, 0.8, 1]
rse = 0.05709034691389371
Building graph
Loading data from ./data/traffic6/validation.tfrecords
2019-08-22 17:38:16.016345: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:38:16.016783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2019-08-22 17:38:16.016883: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 17:38:16.016916: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:38:16.016944: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 17:38:16.016973: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 17:38:16.016996: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 17:38:16.017018: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 17:38:16.017060: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-22 17:38:16.017185: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:38:16.017636: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:38:16.017989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-22 17:38:16.018044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 17:38:16.018067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-22 17:38:16.018079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-22 17:38:16.018377: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:38:16.018791: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-22 17:38:16.019179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)


Epoch: 1
2019-08-22 17:38:31.671150: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 17:38:39.182951: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 3619, loss: 0.02613, epoch time: 88.134s
Saving model, step 3619
Loading saved model from ./models/model_tf/model.ckpt-3619
validation loss: 0.02836, validation rse: 0.71316, validation corr: 0.70850


Epoch: 2
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 3948, loss: 0.02573, epoch time: 72.737s
Saving model, step 3948
Loading saved model from ./models/model_tf/model.ckpt-3948
validation loss: 0.02886, validation rse: 0.71986, validation corr: 0.71131


Epoch: 3
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 4277, loss: 0.02528, epoch time: 73.016s
Saving model, step 4277
Loading saved model from ./models/model_tf/model.ckpt-4277
validation loss: 0.02793, validation rse: 0.70449, validation corr: 0.71838


Epoch: 4
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 4606, loss: 0.02495, epoch time: 76.544s
Saving model, step 4606
Loading saved model from ./models/model_tf/model.ckpt-4606
validation loss: 0.02692, validation rse: 0.68408, validation corr: 0.72710


Epoch: 5
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 4935, loss: 0.02461, epoch time: 74.622s
Saving model, step 4935
Loading saved model from ./models/model_tf/model.ckpt-4935
validation loss: 0.02703, validation rse: 0.68657, validation corr: 0.72804


Epoch: 6
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 5264, loss: 0.02435, epoch time: 70.047s
Saving model, step 5264
Loading saved model from ./models/model_tf/model.ckpt-5264
validation loss: 0.02667, validation rse: 0.67283, validation corr: 0.72903


Epoch: 7
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 5593, loss: 0.02406, epoch time: 66.979s
Saving model, step 5593
Loading saved model from ./models/model_tf/model.ckpt-5593
validation loss: 0.02673, validation rse: 0.68138, validation corr: 0.73925


Epoch: 8
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 5922, loss: 0.02379, epoch time: 68.349s
Saving model, step 5922
Loading saved model from ./models/model_tf/model.ckpt-5922
validation loss: 0.02725, validation rse: 0.68532, validation corr: 0.74357


Epoch: 9
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 6251, loss: 0.02350, epoch time: 66.760s
Saving model, step 6251
Loading saved model from ./models/model_tf/model.ckpt-6251
validation loss: 0.02591, validation rse: 0.66659, validation corr: 0.74757


Epoch: 10
25
50
75
100
125
150
175
200
225
250
275
300
325
global step: 6580, loss: 0.02328, epoch time: 65.944s
Saving model, step 6580
Loading saved model from ./models/model_tf/model.ckpt-6580
validation loss: 0.02545, validation rse: 0.65319, validation corr: 0.75065


Epoch: 11
25
50
75
100
125
150
175
200
225
250
Stop
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: corrupted record at 547039092
	 [[{{node model/input/IteratorGetNext}}]]
  (1) Data loss: corrupted record at 547039092
	 [[{{node model/input/IteratorGetNext}}]]
	 [[model/input/IteratorGetNext/_251]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/Collab/main.py", line 51, in <module>
    main()
  File "/content/drive/Collab/main.py", line 29, in main
    train(para, sess, model, data_generator)
  File "/content/drive/Collab/lib/train.py", line 27, in train
    fetches=[model.loss, model.global_step, model.update])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: corrupted record at 547039092
	 [[node model/input/IteratorGetNext (defined at content/drive/Collab/lib/data_generator.py:85) ]]
  (1) Data loss: corrupted record at 547039092
	 [[node model/input/IteratorGetNext (defined at content/drive/Collab/lib/data_generator.py:85) ]]
	 [[model/input/IteratorGetNext/_251]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node model/input/IteratorGetNext:
 model/input/IteratorV2 (defined at content/drive/Collab/lib/data_generator.py:84)

Input Source operations connected to node model/input/IteratorGetNext:
 model/input/IteratorV2 (defined at content/drive/Collab/lib/data_generator.py:84)

Original stack trace for 'model/input/IteratorGetNext':
  File "content/drive/Collab/main.py", line 51, in <module>
    main()
  File "content/drive/Collab/main.py", line 18, in main
    graph, model, data_generator = create_graph(para)
  File "content/drive/Collab/lib/model_utils.py", line 30, in create_graph
    model = PolyRNN(para, data_generator)
  File "content/drive/Collab/lib/model.py", line 14, in __init__
    self._build_graph()
  File "content/drive/Collab/lib/model.py", line 27, in _build_graph
    self.para.mode, self.para.batch_size)
  File "content/drive/Collab/lib/data_generator.py", line 85, in inputs
    return self.iterator.get_next()
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1947, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
